# 🚀 Supabase 商用環境設定ファイル
# プロジェクトID: mfleexehdteobgsyokex

project_id = "mfleexehdteobgsyokex"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 100

[db]
port = 5432
major_version = 17

[db.pooler]
enabled = true
port = 5432
pool_mode = "transaction"
default_pool_size = 100
max_client_conn = 500

[db.settings]
shared_buffers = "512MB"
work_mem = "128MB"
maintenance_work_mem = "256MB"
effective_cache_size = "2GB"
max_parallel_workers_per_gather = 8

[db.migrations]
enabled = true
schema_paths = ["./migrations"]

[db.seed]
enabled = false

[realtime]
enabled = true

[studio]
enabled = false
api_url = "https://mfleexehdteobgsyokex.supabase.co"

[storage]
enabled = true
file_size_limit = "100MiB"

[auth]
enabled = true
site_url = "https://your-domain.com"
additional_redirect_urls = [
  "https://your-domain.com",
  "https://www.your-domain.com"
]
jwt_expiry = 1800
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 12
password_requirements = "lower_upper_letters_digits_symbols"

[auth.rate_limit]
email_sent = 1
sms_sent = 5
anonymous_users = 0
token_refresh = 30
sign_in_sign_ups = 5
token_verifications = 5

[auth.captcha]
enabled = true
provider = "hcaptcha"
secret = "env(CAPTCHA_SECRET)"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true
max_frequency = "5s"
otp_length = 6
otp_expiry = 1800

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083
deno_version = 1

[edge_runtime.secrets]
DMM_API_ID = "env(DMM_API_ID)"
DMM_AFFILIATE_ID = "env(DMM_AFFILIATE_ID)"
OPENAI_API_KEY = "env(OPENAI_API_KEY)"

[analytics]
enabled = true
port = 54327
backend = "postgres"