# Kubernetes Deployment for Backend Services
# Production-ready with auto-scaling and health checks

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adult-matching-backend
  namespace: adult-matching
  labels:
    app: adult-matching-backend
    version: v1.0.0
    component: api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: adult-matching-backend
  template:
    metadata:
      labels:
        app: adult-matching-backend
        version: v1.0.0
        component: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: adult-matching-backend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: backend-api
        image: adult-matching/backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: supabase_url
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: service_role_key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: WORKER_PROCESSES
          value: "4"
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENVIRONMENT
          value: "production"
        - name: EMBEDDING_CACHE_SIZE
          value: "10000"
        - name: MAX_BATCH_SIZE
          value: "1000"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
          readOnly: true
        - name: log-storage
          mountPath: /app/logs
        - name: temp-storage
          mountPath: /app/data/temp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      - name: log-storage
        emptyDir:
          sizeLimit: 1Gi
      - name: temp-storage
        emptyDir:
          sizeLimit: 5Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - adult-matching-backend
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: adult-matching
  labels:
    app: adult-matching-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: adult-matching-backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: adult-matching
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adult-matching-backend
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: adult-matching
data:
  supabase_url: "https://your-project.supabase.co"
  log_level: "INFO"
  worker_processes: "4"
  embedding_dim: "768"
  batch_size: "1000"
  cache_ttl: "3600"

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: adult-matching
type: Opaque
data:
  # Base64 encoded database URL
  url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYi5leGFtcGxlLmNvbS9hZHVsdF9tYXRjaGluZw==

---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-secret
  namespace: adult-matching
type: Opaque
data:
  # Base64 encoded service role key
  service_role_key: eW91ci1zZXJ2aWNlLXJvbGUta2V5LWhlcmU=

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adult-matching-backend
  namespace: adult-matching

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
  namespace: adult-matching
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 10Gi