import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

function randomBase64Url(bytes = 48) {
  return crypto.randomBytes(bytes).toString('base64')
    .replace(/=/g, '')
    .replace(/\+/g, '-')
    .replace(/\//g, '_');
}

function signJwtHS256(secret, payload) {
  const header = { alg: 'HS256', typ: 'JWT' };
  const iat = Math.floor(Date.now() / 1000);
  const exp = iat + 60 * 60 * 24 * 365; // 1 year
  const body = { iss: 'supabase', iat, exp, ...payload };
  const b64u = (obj) => Buffer.from(JSON.stringify(obj)).toString('base64')
    .replace(/=/g, '')
    .replace(/\+/g, '-')
    .replace(/\//g, '_');
  const data = `${b64u(header)}.${b64u(body)}`;
  const sig = crypto.createHmac('sha256', secret).update(data).digest('base64')
    .replace(/=/g, '')
    .replace(/\+/g, '-')
    .replace(/\//g, '_');
  return `${data}.${sig}`;
}

function main() {
  const outDir = path.resolve('/workspace/docker/env');
  const outPath = path.join(outDir, 'dev.env.generated');

  const POSTGRES_PASSWORD = randomBase64Url(24);
  const SUPABASE_JWT_SECRET = randomBase64Url(48);
  const NEXT_PUBLIC_SUPABASE_ANON_KEY = signJwtHS256(SUPABASE_JWT_SECRET, { role: 'anon', aud: 'authenticated' });
  const SUPABASE_SERVICE_ROLE_KEY = signJwtHS256(SUPABASE_JWT_SECRET, { role: 'service_role', aud: 'authenticated' });
  const NEXT_PUBLIC_SUPABASE_URL = 'http://host.docker.internal:54321';

  const lines = [
    `# Generated by scripts/gen_supabase_keys on ${new Date().toISOString()}`,
    `POSTGRES_PASSWORD=${POSTGRES_PASSWORD}`,
    `SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
    `SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}`,
    `NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}`,
    '',
  ].join('\n');

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outPath, lines, { encoding: 'utf8' });

  console.log('Wrote generated env to:', outPath);
  console.log('\nPreview (copy desired lines into docker/env/dev.env):\n');
  console.log(lines);
}

main();

