# Test comment
openapi: 3.0.3
info:
  title: AVマッチングAPI
  description: AVレコメンド・マッチング用のAPI仕様書
  version: 1.0.0
servers:
  - url: https://<project-ref>.supabase.co/functions/v1
    description: Supabase Edge Functions

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Tag:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        tag_group_id: { type: string }
    Performer:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
    Video:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        description: { type: string }
        tags: { type: array, items: { type: string, description: 'Tag ID' } }
        performers: { type: array, items: { type: string, description: 'Performer ID' } }
        thumbnail_url: { type: string }
        preview_video_url: { type: string }
        source: { type: string }
        published_at: { type: string, format: date-time }

    VideoWithScore:
      allOf:
        - $ref: '#/components/schemas/Video'
        - type: object
          properties:
            score: { type: number }
            reasons: { type: array, items: { type: string } }
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: 'エラーコード (例: "BAD_REQUEST", "UNAUTHORIZED", "NOT_FOUND", "INTERNAL_SERVER_ERROR")'
        message:
          type: string
          description: エラーメッセージ
        details:
          type: object
          description: エラーの詳細情報 (バリデーションエラーのフィールドなど)

paths:
  /videos/feed:
    get:
      summary: 動画フィード取得
      description: ユーザーの認証状態と学習状態に応じて、レコメンドまたは多様性を考慮した動画リストを返します。非ログインユーザーも利用可能です。
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            description: 取得する動画の最大数
      responses:
        '200':
          description: 動画リスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VideoWithScore'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証失敗（トークンが無効、または有効期限切れ）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /update_user_embedding:
    post:
      summary: ユーザー埋め込み更新
      description: 行動履歴に基づいてユーザーのembeddingを更新
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                strategy:
                  type: string
                  enum: [online, batch]
                window_days:
                  type: integer
                  default: 30
      responses:
        '200':
          description: 更新結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /delete_account:
    delete:
      summary: アカウント削除
      description: Supabase Authユーザーを削除（Service Role必須）
      responses:
        '200':
          description: 削除結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
