name: Deploy Docs to GitHub Pages

on: 
  push:
    branches:
      - main
    paths:
      - 'docs/openapi.yaml' # openapi.yaml が変更された場合のみトリガー
  workflow_dispatch: # 手動でワークフローをキックできるようにする

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages