name: Deploy DB Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'db/migrations/**/*.sql'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'db/migrations/**/*.sql'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >- # health-check for postgres
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL to be ready
        run: |
          sleep 10

      - name: Create dummy auth schema, users table, and roles
        run: |
          PGPASSWORD=password psql -h localhost -p 5432 -U user -d test_db -c "CREATE SCHEMA IF NOT EXISTS auth;"
          PGPASSWORD=password psql -h localhost -p 5432 -U user -d test_db -c "CREATE TABLE IF NOT EXISTS auth.users (id UUID PRIMARY KEY, email TEXT UNIQUE, created_at TIMESTAMPTZ DEFAULT NOW());"
          PGPASSWORD=password psql -h localhost -p 5432 -U user -d test_db -c "CREATE ROLE authenticated;"
          PGPASSWORD=password psql -h localhost -p 5432 -U user -d test_db -c "CREATE ROLE anon;"

      - name: Install PostgreSQL client and pgvector
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository 'deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-13 postgresql-13-pgvector

      - name: Create dummy auth.uid() function
        run: |
          PGPASSWORD=password psql -h localhost -p 5432 -U user -d test_db <<'EOF'
          CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE plpgsql IMMUTABLE AS $
          BEGIN
            RETURN '00000000-0000-0000-0000-000000000000';
          END;
          $;
          EOF

      - name: Enable pgvector extension
        run: |
          PGPASSWORD=password psql -h localhost -p 5432 -U user -d test_db -c "CREATE EXTENSION IF NOT EXISTS vector;"

      - name: Apply migrations
        run: |
          PGPASSWORD=password psql -h localhost -p 5432 -U user -d test_db -f db/migrations/20250818000000000_initial.sql

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download SchemaSpy and JDBC Driver
        run: |
          curl -L -o schemaspy.jar https://github.com/schemaspy/schemaspy/releases/download/v6.2.4/schemaspy-6.2.4.jar
          curl -L -o postgresql-jdbc.jar https://jdbc.postgresql.org/download/postgresql-42.7.3.jar

      - name: Generate DB Docs
        run: |
          java -jar schemaspy.jar \
            -t pgsql \
            -host localhost \
            -port 5432 \
            -db test_db \
            -u user \
            -p password \
            -o docs/db-docs \
            -dp postgresql-jdbc.jar

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/db-docs
          publish_branch: gh-pages
          destination_dir: ${{ github.event_name == 'pull_request' && format('pr-preview/{0}/db-docs', github.event.pull_request.number) || 'db-docs' }}
